# Create Train stations
from src.train_station import TrainStation

WIDTH, HEIGHT = 1600, 900

#s2 lines
blankenfelde = TrainStation("Blankenfelde", int(WIDTH * 0.5), int(HEIGHT * 0.925), bold=True)
mahlow = TrainStation("Mahlow", int(WIDTH * 0.5), int(HEIGHT * 0.9))
lichtenrade = TrainStation("Lichtenrade", int(WIDTH * 0.5), int(HEIGHT * 0.875))
schichaueweg = TrainStation("Schichauweg", int(WIDTH * 0.5), int(HEIGHT * 0.85))
buckower_chaussee = TrainStation("Buckower Chaussee", int(WIDTH * 0.5), int(HEIGHT * 0.825))
marienfelde = TrainStation("Marienfelde", int(WIDTH * 0.5), int(HEIGHT * 0.8))
attilastrasse = TrainStation("Attilastraße", int(WIDTH * 0.475), int(HEIGHT * 0.775))
priesterweg = TrainStation("Priesterweg", int(WIDTH * 0.45), int(HEIGHT * 0.75))
suedkreuz = TrainStation("Südkreuz", int(WIDTH * 0.45), int(HEIGHT * 0.7), bold=True)
yorckstr = TrainStation("Yorckstraße", int(WIDTH * 0.45), int(HEIGHT * 0.62))
anhalter_bahnhof = TrainStation("Anhalter Bahnhof", int(WIDTH * 0.45), int(HEIGHT * 0.55))
potsdamer_platz = TrainStation("Potsdamer Platz", int(WIDTH * 0.45), int(HEIGHT * 0.5))
brandenburger_tor = TrainStation("Brandenburger Tor", int(WIDTH * 0.45), int(HEIGHT * 0.45))
friedrichstr = TrainStation("Friedrichstraße", int(WIDTH * 0.5), int(HEIGHT * 0.4))
oranienburger_str = TrainStation("Oranienburger Str.", int(WIDTH * 0.5), int(HEIGHT * 0.36))
nordbahnhof = TrainStation("Nordbahnhof", int(WIDTH * 0.5), int(HEIGHT * 0.34))
humboldthain = TrainStation("Humboldthain", int(WIDTH * 0.5), int(HEIGHT * 0.32))
gesundbrunnen = TrainStation("Gesundbrunnen", int(WIDTH * 0.5), int(HEIGHT * 0.3), bold=True)
bornholmer_str = TrainStation("Bornholmer Str.", int(WIDTH * 0.515), int(HEIGHT * 0.25))
pankow = TrainStation("Pankow", int(WIDTH * 0.525), int(HEIGHT * 0.225), bold=True)
pankow_heinersdorf = TrainStation("Pankow-Heinersdorf", int(WIDTH * 0.55), int(HEIGHT * 0.2))
blankenburg = TrainStation("Blankenburg", int(WIDTH * 0.57), int(HEIGHT * 0.18), bold=True)
karow = TrainStation("Karow", int(WIDTH * 0.6), int(HEIGHT * 0.15), bold=True)
buch = TrainStation("Buch", int(WIDTH * 0.61), int(HEIGHT * 0.14))
roentgental = TrainStation("Röntgental", int(WIDTH * 0.62), int(HEIGHT * 0.13))
zepernick = TrainStation("Zepnick", int(WIDTH * 0.63), int(HEIGHT * 0.12))
bernau_friedenstal = TrainStation("Bernau-Friedenstal", int(WIDTH * 0.64), int(HEIGHT * 0.11))
bernau = TrainStation("Bernau", int(WIDTH * 0.65), int(HEIGHT * 0.1), bold=True)

# s25 line
suedende = TrainStation("Südende", int(WIDTH * 0.425), int(HEIGHT * 0.775))
lankwitz = TrainStation("Lankwitz", int(WIDTH * 0.4), int(HEIGHT * 0.8))
lichterfelde_ost = TrainStation("Lichterfelde Ost", int(WIDTH * 0.375), int(HEIGHT * 0.825))
osdorfer_str = TrainStation("Osdorfer Str.", int(WIDTH * 0.35), int(HEIGHT * 0.85))
lichterfelde_sued = TrainStation("Lichterfelde Süd", int(WIDTH * 0.325), int(HEIGHT * 0.875))
teltow_stadt = TrainStation("Teltow Stadt", int(WIDTH * 0.25), int(HEIGHT * 0.9), bold=True)
wollankstr = TrainStation("Wollankstr.", int(WIDTH * 0.5), int(HEIGHT * 0.225))
schoenholz = TrainStation("Schönholz", int(WIDTH * 0.45), int(HEIGHT * 0.2))
alt_reinickendorf = TrainStation("Alt-Reinickendorf", int(WIDTH * 0.42), int(HEIGHT * 0.19))
karl_bonhoeffer_nervenklinik = TrainStation("Karl-Bonhoeffer-Nevenklinik", int(WIDTH * 0.39), int(HEIGHT * 0.19))
eichborndamm = TrainStation("Eichborndamm", int(WIDTH * 0.36), int(HEIGHT * 0.19))
tegel = TrainStation("Tegel", int(WIDTH * 0.33), int(HEIGHT * 0.17))
schulzendorf = TrainStation("Schulzendorf", int(WIDTH * 0.31), int(HEIGHT * 0.15))
heiligensee = TrainStation("Heiligensee", int(WIDTH * 0.29), int(HEIGHT * 0.13))
hennigsdorf = TrainStation("Hennigsdorf", int(WIDTH * 0.27), int(HEIGHT * 0.11), bold=True)
